version: '3.8'

services:
  api:
    build: .
    container_name: egen_security_api
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - APP_ENV=development
      - DEBUG=True
      - PORT=8000
      - HOST=0.0.0.0
      - MONGODB_URI=mongodb://mongodb:27017/egen_security_ai
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:6.0
    container_name: egen_security_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:
