version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - APP_ENV=production
      - PORT=5000
      - HOST=0.0.0.0
      - MODEL_DEVICE=cpu
      - MODEL_PRECISION=fp16
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
    networks:
      - egen-security-network
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - egen-security-network
    restart: unless-stopped

networks:
  egen-security-network:
    driver: bridge

volumes:
  models:
  logs: 